### ISSUE TITLE
[Meta] Showcase an export of HTML/CSS/JS charts as images

### ISSUE THREAD

**Issue by armiol** [TeamDev-IP/JxBrowser-Gallery#1]
In scope of this issue, an application demonstrating JxBrowser capabilities on server-side chart rendering should be created.

## Features

**Pre-defined data array**: something like [flights data](https://data.world/bob-wakefield/flights).

As a user of the app...

- upon opening the web page, I should be presented with a pre-loaded panel with stats on pre-loaded data files (description, total number, available columns), and several charts, visualising this data array.
- I should be able to tweak the chart details by using the corresponding controls.
- I should be able to export the charts to various image formats (PNG, SVG?), and to PDF by clicking on the corresponding button.

### Open questions

- Choosing the dataset to pre-load. Suggestions are welcome.
- Depending on the dataset, selecting the chart types.

## Architecture

This should be a single-page web application, built on top of JVM.

- Build chain: Gradle, Java 17.
- Java server: JxBrowser 8.0.0 (most recent EAP available), Micronaut.
- Web client: JavaScript / TypeScript, HTML, CSS.

Suggested JS libraries for charting: 

 - https://www.chartjs.org/
 - https://d3js.org/

**Comment by dmitrykuzmin** [comment]
Done in scope of the linked PRs.
