### ISSUE TITLE
[Meta] Showcase an export of table data to PDF

### ISSUE THREAD

**Issue by armiol** [TeamDev-IP/JxBrowser-Gallery#3]
We want to create a show-case for JxBrowser PDF export capabilities. In scope of this issue, a gallery application for that should be created.

## Features

**Pre-defined data array** — I suggest we pick something different from what we picked for #1.

As a user of the app...

- upon opening the web page, I should be presented with a pre-loaded table (~20 rows visible), with simple filtering for some headers.
- I should be able to filter data using the respective controls.
- I should be able to export the table to PDF by clicking on the corresponding button.

## Architecture

This should be a single-page web application, built on top of JVM.

- Build chain: Gradle, Java 17, latest _released_ Kotlin (as of moment of writing, it's Kotlin 1.9.23).
- Java server: JxBrowser 8.0.0 (most recent EAP available) + JxBrowser-Kotlin library, Ktor.
- Web client: JavaScript / TypeScript, HTML, CSS.

**Comment by dmitrykuzmin** [comment]
Done in scope of the linked PRs.
