### ISSUE TITLE
Browser fails to render the animation if executed locally

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [TeamDev-IP/JxBrowser-Gallery#8]
Steps to reproduce:

1. Run the example with the following command: `./gradlew :examples:pomodoro:run`.
2. Choose `Short break` timer.
3. Choose `Pomodoro` timer.
4. See the tomato is not fully rendered now.

<details><summary>Screen recording</summary>

https://github.com/TeamDev-IP/JxBrowser-Kotlin/assets/13679188/6d6bc65e-ec00-4878-a174-83632283541e
</details>

**Please note:** it works as expected if the app is executed as a separate file: `runDistributable` instead of `run`.
I was unable to reproduce this in Google Chrome. It can be a failure of WebGL/Three.js, but I'm not really sure who to blame. Failed parts repeat the geometry of the model, looks like texture image was partially unloaded (?).

The bug is reproducible on macOS x86. Works fine on ARM machines.

**Comment by vladimir-ikryanov** [comment]
@yevhenii-nadtochii @Danil-Didkovskiy Please check DevTools console. Some JS code can be executed only in a secure scheme, e.g. HTTPS. Local HTML file has the FILE scheme which is not secure. In DevTools Console you will see the corresponding error message if that's the case.

**Comment by Danil-Didkovskiy** [comment]
I was unable to reproduce the issue locally on macOS 14 and Windows 10. I tried both `run` and `runDistributable`. In both cases, I observed smooth animation without any rendering issues.

**Comment by vladimir-ikryanov** [comment]
It works without any rendering issues in my Mac environment as well:

```
./gradlew :compose:pomodoro:run
```

https://github.com/user-attachments/assets/ecd19f6d-e492-4d17-99a9-773468092210
